### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Hanishdhamija19** [jackpocket/android_scratchoff#16]
Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
com.jackpocket.scratchoff.ScratchableLayoutDrawer.initializePostDisplay

android.graphics.Bitmap.createBitmap + 750 (Bitmap.java:750)
--
  | com.jackpocket.scratchoff.ScratchableLayoutDrawer.initializePostDisplay + 90 (ScratchableLayoutDrawer.java:90)
  | com.jackpocket.scratchoff.ScratchableLayoutDrawer.access$200 + 18 (ScratchableLayoutDrawer.java:18)
  | com.jackpocket.scratchoff.ScratchableLayoutDrawer$2.run + 80 (ScratchableLayoutDrawer.java:80)
  | com.jackpocket.scratchoff.ViewHelper$1.onGlobalLayout + 22 (ViewHelper.java:22)

**Comment by mattsilber** [comment]
Is it possible there's something in your implementation preventing the View's drawing cache from being created? 

Can you provide relevant sample code of your implementation and image resource(s) this is crashing with to help diagnose your issue?
