### ISSUE TITLE
Scratch Attempt

### ISSUE THREAD

**Issue by ollyc2015** [jackpocket/android_scratchoff#8]
Is it possible to have a scratch attempt count and only reveal on the set count value?

I.E. set scratch reveal after 2 ontouch events have occurred on specified scratch controller. 

I ask this because I'm making a little quiz app and I am setting the correct answer behind one of four scratch controllers. There is bound to be a scenario where someone has clicked on a scratch pad by mistake so I'm trying to think of a solution.

**Comment by mattsilber** [comment]
This wouldn't directly be possible through the library since the reveal is based of percentage scratched. But, you could probably achieve what you want with some kind of transparent custom view on top, where the first click hides it to reveal the scratchable surface beneath.

**Comment by mattsilber** [comment]
Closed as it's been almost a year without a response and not particularly related
